### ISSUE TITLE
Randomize the order of blogs

### ISSUE THREAD

**Issue by healeycodes** [searchableguy/awesomeblog-club#19]
Although users will probably be searching using tags or keywords, it would be nice if the order was randomized to further the goal of introducing new blogs to people.

Some ideas off the top of my head for implementation:

- A GitHub action to randomize the order of `database.json` and commit every day
- `getBlogs()` in `store.ts` shuffles the blogs before returning
- The component `SearchList` randomizes the order

I'm happy to implement one of the bottom two 👍

**Comment by searchableguy** [comment]
Thanks for opening the issue. I was going to do that myself eventually. There are few smaller issues I would like to fix but they are all going to break the current one big file approach. I will refactor the site to use a directory of file instead of a single file today and implement the sort to be random.

:)

**Comment by healeycodes** [comment]
@searchableguy Awesome, I look forward to checking it out 😄

**Comment by searchableguy** [comment]
@healeycodes done
https://github.com/searchableguy/awesomeblog-club/commit/7ca3ee8c2e766bf05683c5507942259573ac4e13
